TollFreeCalculator/Models/ErrorViewModel.cs
using System;

namespace TollFreeCalculator.Models
{
     public class ErrorViewModel
     {
          public string RequestId { get; set; }

          public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
     }
}

TollFreeCalculator/Models/TollFreeVehicle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TollFreeCalculator.Models
{
     public class TollFreeVehicle
     {
          public List<string> tollFreeVehicle { get; set; }
     }
}

TollFreeCalculator/Models/TollTimes.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TollFreeCalculator.Models
{
	public class TollTimes
	{
		public Dictionary<string, string> MyMappings { get; set; }
		[Required(ErrorMessage = "Please Select the valid date")]
		  [DataType(DataType.Date)]
		[DisplayFormat(DataFormatString = "{0:dd/M/yy}", ApplyFormatInEditMode = true)]
		public DateTime? StartDate { get; set; }

		[Required(ErrorMessage = "Please Select the toll count")]
		public TollCount? TollCount { get; set; }
        /// <summary>
		/// Used to Maintain the Total Toll Amount
		/// </summary>
		public int SumAmount { get; set; }
		  /// <summary>
		  /// Contains List of Vehicles
		  /// </summary>
		  [Required(ErrorMessage = "Please select the vehcile type")]
		public List<string> VehicleList { get; set; }

	 }
	 /// <summary>
	 /// TollFree Vehicle List
	 /// </summary>
	public enum TollFreeVehicles
	{
		Motorbike = 0,
		Tractor = 1,
		Emergency = 2,
		Diplomat = 3,
		Foreign = 4,
		Military = 5,
	}
	 /// <summary>
	 /// TollCount
	 /// </summary>
	public enum TollCount
	{
		One = 1,
		Two = 2,
		Three = 3,
		Four = 4,
		Five = 5,
		Six = 6,
		Seven = 7,
		Eight = 8,
		Nine = 9,
		Ten = 10,
	 }

	
}

TollFreeCalculator/Models/TollTimes_Old.cs
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TollFreeCalculator.Models
{
     /// <summary>
     /// Toll timing class used to set the time
     /// </summary>
     public class TollTimes_Old
     {
          /// <summary>
          /// config property used to read configuration from appsetting.json
          /// </summary>
         // private readonly IConfiguration _config;

          public Dictionary<string, string> Value { get; set; }

     }
}

TollFreeCalculator/Controllers/TollFreeCalculatorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TollFreeCalculator.Models;

namespace TollFreeCalculator.Controllers
{
	 public class TollFreeCalculatorController : Controller
	 {
		  #region Varible Declartion 
		  private readonly IOptions<TollTimes> tollConfig;
		  Dictionary<int, int> tollFreeDate = new Dictionary<int, int>();
		  private int tollTollFee = 0;
          #endregion

          #region Constructor
          public TollFreeCalculatorController(ILogger<TollFreeCalculatorController> logger,
			IOptions<TollTimes> _tollconfig)
		  {
			   tollConfig = _tollconfig;
		  }
          #endregion

          #region Action methods
          /// <summary>
          /// 
          /// </summary>
          /// <returns></returns>
          public IActionResult Home()
		  {
			   
			   TollTimes tollTimes = new TollTimes();
			   tollTimes.VehicleList = tollConfig.Value.VehicleList;
			   tollTimes.MyMappings = tollConfig.Value.MyMappings;
			   ViewBag.IsShow = false;
			   return View(tollTimes);
		  }

		  [HttpPost]
		  public ActionResult GetTollFee(TollTimes contact, IFormCollection form)
		  {

			   var dateTravelled =Request.Form["StartDate"];
			   var vehcileType = Request.Form["VehicleList"].ToString();
			   var tollCount = Request.Form["TollCount"].ToString();
			   var tollCrossedTimes = Request.Form["MyMappings"].ToString();
			   contact.MyMappings = tollConfig.Value.MyMappings;
			   contact.VehicleList = tollConfig.Value.VehicleList;
			   ViewBag.IsShow = false;
			   if (Request.Form["Calculate"].ToString() != string.Empty)
			   {
					if (ModelState.IsValid)
					{
						 ViewBag.IsShow = true;
						 if (IsTollFreeVehicle(vehcileType))
						 {
							  contact.SumAmount = 0;
							  return View("Home", contact);
						 }
						 if (IsTollFreeDate(Convert.ToDateTime(dateTravelled)))
						 {
							  contact.SumAmount = 0;
							  return View("Home", contact);
						 }
						 contact.SumAmount = GetTotalTollFee(tollCrossedTimes);
					}
			   }
			   return View("Home", contact);
		  }

          #endregion

          #region Private Methods
          /// <summary>
          /// Method Used to get the Total Toll Fee 
          /// </summary>
          /// <returns>Total Toll Fee</returns>
          private int GetTotalTollFee(string crossedTimes)
		  {
			   string[] times = crossedTimes.Split(",");
			   string prevTollCrossed = times[0];
			   foreach (string time in times)
			   {
					int currentFee = GetTollFee(time);
					int prevTollFee = GetTollFee(prevTollCrossed);
					// MultiPassage Rule 
					if (prevTollCrossed == time || time== "06 30 - 06 59")
					{
						 if (tollTollFee > 0) tollTollFee -= prevTollFee;
						 if (currentFee >= prevTollFee) prevTollFee = currentFee;
						 tollTollFee += prevTollFee;
					}
					else
					{
						 tollTollFee += currentFee;
					}
					prevTollCrossed = time;
			   }
			   if (tollTollFee > 60) tollTollFee = 60;
			   return tollTollFee;
		  }

		  /// <summary>
		  /// Method used to get the Toll fee for the particular Toll
		  /// </summary>
		  /// <returns>Toll Fee</returns>
		  private int GetTollFee(string time)
		  {
			   string outValue;
			   int fee = 0;
			   if (tollConfig.Value.MyMappings.TryGetValue(time, out outValue))
			   {
					outValue = outValue.Replace("kr", "");
					fee = Convert.ToInt32(outValue);
			   }
			   return fee;
		  }
		  /// <summary>
		  /// Method Used to Check the date is toll free date or not
		  /// </summary>
		  /// <returns>True or False</returns>
		  private Boolean IsTollFreeDate(DateTime date)
		  {
			   int year = date.Year;
			   int month = date.Month;
			   int day = date.Day;
			   if (date.DayOfWeek == DayOfWeek.Saturday || date.DayOfWeek == DayOfWeek.Sunday)
					return true;
			   if (year == 2013)
			   {
					if (tollFreeDate.Contains(new KeyValuePair<int, int>(month, day)))
						 return true;

			   }
			   return false;

		  }
		  /// <summary>
		  /// Method used to check the vehcile is TollFree or Not
		  /// </summary>
		  /// <returns>True or False</returns>
		  private bool IsTollFreeVehicle(string vehicle)
		  {
			   if (Enum.IsDefined(typeof(TollFreeVehicles), vehicle))
					return true;
			   else return false;
		  }

		  /// <summary>
		  /// Method used maintain the tollfree date
		  /// </summary>
		  private void TollFreeDate()
		  {
			   tollFreeDate.Add(1, 1);
			   tollFreeDate.Add(3, 28);
			   tollFreeDate.Add(3, 29);
			   tollFreeDate.Add(4, 1);
			   tollFreeDate.Add(4, 30);
			   tollFreeDate.Add(5, 1);
			   tollFreeDate.Add(5, 8);
			   tollFreeDate.Add(5, 9);
			   tollFreeDate.Add(6, 5);
			   tollFreeDate.Add(6, 6);
			   tollFreeDate.Add(6, 21);
			   tollFreeDate.Add(7, 1);
			   tollFreeDate.Add(7, 11);
			   tollFreeDate.Add(11, 1);
			   tollFreeDate.Add(12, 24);
			   tollFreeDate.Add(12, 25);
			   tollFreeDate.Add(12, 26);
			   tollFreeDate.Add(12, 31);

		  }
		
	 }
     #endregion
}

TollFreeCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TollFreeCalculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
     <header>
          <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
              
               <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TollFreeCalculator</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                         <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                         <ul class="navbar-nav flex-grow-1">
                              <li class="nav-item">
                                   <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                              </li>
                              <li class="nav-item">
                                   <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                              </li>
                         </ul>
                    </div>
               </div>
          </nav>
     </header>
     <div class="container">
          <main role="main" class="pb-3">
               @RenderBody()
          </main>
     </div>

     <footer class="border-top footer text-muted">
          <div class="container">
               &copy; 2021 - TollFreeCalculator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
          </div>
     </footer>
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
     <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
     <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
     <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
     <script src="~/js/site.js" asp-append-version="true"></script>

     @RenderSection("Scripts", required: false)
     }
</body>
</html>

TollFreeCalculator/Views/TollFreeCalculator/GeneralInfo.cshtml
@{
     ViewData["Title"] = "GeneralInfo";
}

<h1>Times and amounts for congestion tax in Gothenburg</h1>
<p><b>Congestion tax is levied at fixed times for vehicles driven into and out of Gothenburg.</b></p>
<p>The maximum amount per day and vehicle is SEK 60.</p>
<p>Tax is not levied on public holidays, the day before the public holiday or during the month of July.</p>
<p>Read more about which <a href="https://www.transportstyrelsen.se/sv/vagtrafik/Trangselskatt/Trangselskatt-i-goteborg/Tider-och-belopp-i-Goteborg/dagar-da-trangselskatt-inte-tas-ut-i-goteborg/"> days when congestion tax is not levied in Gothenburg</a></p>

TollFreeCalculator/Views/TollFreeCalculator/Home.cshtml
@model TollTimes
<!DOCTYPE html>

<html lang="en">
<head>
     <title>Toll Fee Calculator</title>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    
     <style>
          /* Remove the navbar's default margin-bottom and rounded borders */
          .navbar {
               margin-bottom: 0;
               border-radius: 0;
          }

          /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
          .row.content {
               height: 1000px;
          }

          /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
          .row.passagerule {
               height: 45px;
          }

          /* Set gray background color and 100% height */
          .sidenav {
               padding-top: 20px;
               background-color: #f1f1f1;
               height: 100%;
          }

          /* Set black background color, white text and some padding */
          footer {
               background-color: #555;
               color: white;
               padding: 15px;
          }

          .td.content {
               width: 300px;
               height: 50px;
          }

          tollselection {
               height: 50px;
          }

          .field-validation-error {
               color: red;
          }

          .validation-summary-errors {
               font-weight: bold;
               color: red;
          }

          .error {
               color: red;
          }
          .form-control
          {
               width:150px;
          }
          .navbar-inverse
          {
               background-color: #F5F5F5;
               border-color: #F5F5F5;
               border: 1px solid #e3e3e3;
               padding:2px;
          }

          .text {
  fill: url(#gr-radial);
}

/* Other styles */
/*html, body {
  height: 100%;
}*/

/*body {
  background: #222 -webkit-linear-gradient(0deg, #222 50%, #272727 50%);
  background: #222 linear-gradient(90deg, #222 50%, #272727 50%);
  background-size: .2em 100%;
  font: 14.5em/1 Open Sans, Impact;
  text-transform: uppercase;
  margin: 0;
}*/

svg {
  position: absolute;
  width: 100%;
  height: 100%;
  background: #222 -webkit-linear-gradient(0deg, #f5f5f5 50%, #f5f5f5 50%);
  background: #222 linear-gradient(90deg, #f5f5f5 50%, #f5f5f5 50%);
  background-size: .2em 100%;
  font: 14.5em/1 Open Sans, Impact;
  text-transform: uppercase;
  margin: 0;
}

     </style>
</head>
<body>
     
     <nav class="navbar navbar-inverse">
          <div class="container-fluid">
               <marquee behavior="scroll" direction="left">TOLL FEE CALCULATOR</marquee>
          </div>
          <svg viewBox="0 0 600 300">

               <!-- Gradient -->
               <radialGradient id="gr-radial"
                               cx="50%" cy="50%" r="70%">
                    <!-- Animation for radius of gradient -->
                    <animate attributeName="r"
                             values="0%;150%;100%;0%"
                             dur="5s" repeatCount="indefinite" />
                    <!-- Animation for colors of stop-color -->
                    <stop stop-color="#FFF" offset="0">
                         <animate attributeName="stop-color"
                                  values="#333;#FFF;#FFF;#333"
                                  dur="5s" repeatCount="indefinite" />
                    </stop>
                    <stop stop-color="rgba(55,55,55,0)" offset="100%" />
               </radialGradient>

               <!-- Text -->
               <text text-anchor="middle"
                     x="50%"
                     y="50%"
                     dy=".35em"
                     class="text">
                    TOLL FEE CALCULATOR
               </text>
          </svg>
     </nav>

     <div class="container-fluid text-center">
          <div class="row content">
               <div class="col-sm-8 text-left">
                    <h1>Times and amounts for congestion tax in Gothenburg</h1>
                    <h3>Congestion tax is levied at fixed times for vehicles driven into and out of Gothenburg.</h3>
                    <p>
                         The maximum amount per day and vehicle is SEK 60.

                         Tax is not levied on public holidays, the day before the public holiday or during the month of July.
                    </p>
                    <hr>
                    <div>
                    </div>
                    <div>
                         <table>
                              @using (Html.BeginForm("GetTollFee", "TollFreeCalculator", FormMethod.Post))
                              {
                                   <tr>

                                        <td class=" td content">
                                             <p> Please select date when you travelled</p>
                                        </td>
                                        <td style="          width: 240px;
          margin-left: 30px;
          margin-right: 30px;
          height: 50px">
                                             @Html.EditorFor(m => m.StartDate, new { htmlAttributes = new { @class = "datepicker" }, style = "width:240px;height:35px" })
                                        </td>
                                   </tr>
                                   <tr>
                                        <td>
                                             <p> Please select vehicle type you travelled</p>
                                        </td>
                                        <td style="width: 240px; margin-left: 30px; margin-right: 30px; height: 50px">
                                             @Html.DropDownListFor(m => m.VehicleList, new SelectList(Model.VehicleList, ""), "Select", new { @class = "form-control valid" })

                                        </td>
                                        
                                   </tr>
                                   <tr>
                                        <td>
                                             <p> Please select the no of toll you crossed</p>
                                        </td>
                                        <td style="width:240px;margin-left:30px; margin-right:30px;height:50px">
                                             @Html.DropDownListFor(model => model.TollCount, new SelectList(Enum.GetValues(typeof(TollCount))), "Select", new { @class = "form-control valid", @onchange = "this.form.submit();" })
                                        </td>
                                   </tr>
                                   @for (int i = 1; i <= Convert.ToInt32(Model.TollCount); ++i)
                                   {
                                        <tr>
                                             <td style="height: 50px">
                                                  <p> Please select when you crossed the @i toll</p>
                                             </td>
                                             <td style="width:240px;margin-left:30px; margin-right:30px;height:50px">
                                                  @Html.DropDownListFor(m => m.MyMappings, new SelectList(Model.MyMappings.Keys, "Key"), new { @class = "form-control valid" })
                                             </td>
                                        </tr>
                                   }
                                   <tr>
                                        <td>
                                             <input type="submit" id="btnSubmit" name="Calculate" value="Calculate" class="btn btn-success" />
                                        </td>
                                        <td>
                                             @if (ViewBag.IsShow)
                                             {
                                                  <input type="text" name="Sum Amount" value="@Model.SumAmount" class="btn btn-success" />
                                             }

                                        </td>
                                   </tr>

                              }
                         </table>
                    </div>
               </div>
               <div class="col-sm-4 sidenav">
                    <div class="well">
                         <p>@Html.Partial("TollFeeDisplay")</p>
                    </div>
                    <hr>
                    <div class="well">
                         <p>@Html.Partial("MultiPassageRule")</p>
                    </div>
               </div>
          </div>
     </div>

     <footer class="container-fluid text-center">
          <p>Footer Text</p>
     </footer>

</body>

</html>

<script type="text/javascript">
     $(document).ready(function () {
          $('#StartDate').datepicker({
               orientation: "left",
               autoclose: true,
               format: 'dd-M-yy',
               clearBtn: true
          });
          $("#btnSubmit").click(function () {
               document.getElementById("btnSubmit").value = "Calculating...";
          }
          );

          //function SetValue() {
          //     document.getElementById("btnSubmit").value = "Calculating...";
          //}
     });
</script>

TollFreeCalculator/Views/TollFreeCalculator/MultiPassageRule.cshtml
@{
    ViewData["Title"] = "MultiPassageRule";
}

     <h1>The multi-passage rule</h1>
     <p>The multi-passage rule means that a car that passes several toll stations within 60 minutes is only taxed once. The amount to be paid is the maximum amount of those passages.</p>

TollFreeCalculator/Views/TollFreeCalculator/TollSelection.cshtml
<h1> Toll Selection</h1>

TollFreeCalculator/Views/TollFreeCalculator/Tollfeedisplay.cshtml
@model TollTimes


	 <h2> Times and costs for congestion tax in Gothenburg</h2>

<div>
	@if(Model.MyMappings.Count()!=0)
	{
		<table>			
			 <tboby>
			 	 <tr>
			 	 	 <td style="width:150px">
			 	 	 	 @Html.Label("Times (time)")
			 </td>
					 <td>
					 	 @Html.Label("Tax amount (SEK)")
					 </td>
			 </tr>
			 @foreach (var item in Model.MyMappings)
			 {

			 	 <tr>
			 	 	 <td>
			 	 	 	 @Html.LabelForModel(item.Key)
			 </td>
			 <td>
			 	 @Html.LabelForModel(item.Value)
			 </td>
			 </tr>
		}
			 </tboby>
		</table>

	}


</div>